"""Batch 3: is the gross Sharpe from Batch 2 real, or is it the best of several tries?

Run: python run_batch3.py

Every candidate evaluated here is appended to trials.jsonl, and the deflated Sharpe is
computed against that count. The trial log is committed to the repo on purpose: a deflated
Sharpe quoted without a verifiable trial count is just a Sharpe with extra decimals.
"""

from __future__ import annotations

import logging

import numpy as np
import pandas as pd

from trendlab import FRICTIONLESS, CostModel, buy_and_hold, run
from trendlab.data import CANDIDATES, dollar_volume, load_frames, point_in_time_universe
from trendlab.portfolio import target_weights
from trendlab.signals import combined_forecast
from trendlab.validate import (
    deflated_sharpe_ratio,
    effective_breadth,
    log_trial,
    probabilistic_sharpe_ratio,
    read_trials,
    sharpe_ratio,
    spa_test,
    walk_forward,
)

logging.basicConfig(level=logging.WARNING, format="%(message)s")

CAPITAL = 1_000.0
TARGET_VOL = 0.15
MAX_GROSS = 2.0

# The trial surface, fixed before looking at any result. Ten rule sets built from four span
# pairs. Written out explicitly rather than generated by a loop over a parameter grid, so
# that the number of things tried is legible and cannot quietly grow.
RULE_SETS: dict[str, tuple[tuple[int, int], ...]] = {
    "ewmac 8/32": ((8, 32),),
    "ewmac 16/64": ((16, 64),),
    "ewmac 32/128": ((32, 128),),
    "ewmac 64/256": ((64, 256),),
    "ewmac 8/32+16/64": ((8, 32), (16, 64)),
    "ewmac 16/64+32/128": ((16, 64), (32, 128)),
    "ewmac 32/128+64/256": ((32, 128), (64, 256)),
    "ewmac 16/64+64/256": ((16, 64), (64, 256)),
    "ewmac 3-rule (batch 2)": ((16, 64), (32, 128), (64, 256)),
    "ewmac 4-rule": ((8, 32), (16, 64), (32, 128), (64, 256)),
}


def main() -> None:
    frames = load_frames(CANDIDATES, since="2017-01-01")
    prices = pd.DataFrame({s: f["close"] for s, f in frames.items()}).sort_index()
    universe = point_in_time_universe(dollar_volume(frames).reindex_like(prices), n=10)
    returns = prices.pct_change()

    print(f"bars {prices.shape[0]}, {prices.index[0].date()} to {prices.index[-1].date()}")
    print(
        f"effective breadth (last 250d): {effective_breadth(returns[universe.iloc[-1].index]):.1f}"
    )
    print(f"rule sets evaluated this run: {len(RULE_SETS)}")
    print()

    net_returns: dict[str, pd.Series] = {}
    gross_returns: dict[str, pd.Series] = {}
    rows = []

    for name, rules in RULE_SETS.items():
        forecast = combined_forecast(prices, rules=rules)
        weights = target_weights(
            prices, forecast, universe=universe, target_vol=TARGET_VOL, max_gross=MAX_GROSS
        )
        net = run(prices, weights, costs=CostModel(), initial_capital=CAPITAL)
        gross = run(prices, weights, costs=FRICTIONLESS, initial_capital=CAPITAL)

        # Trim the burn-in: leading zero-weight bars are not evidence either way.
        first = weights.abs().sum(axis=1).replace(0.0, np.nan).first_valid_index()
        net_returns[name] = net.returns.loc[first:]
        gross_returns[name] = gross.returns.loc[first:]

        log_trial(name, {"rules": [list(r) for r in rules], "target_vol": TARGET_VOL}, net.stats())
        rows.append(
            (
                name,
                sharpe_ratio(gross_returns[name], annualise=True),
                sharpe_ratio(net_returns[name], annualise=True),
                net.stats()["ann_cost_drag"],
            )
        )

    print(f"{'rule set':<26}{'gross SR':>10}{'net SR':>9}{'cost/yr':>10}")
    print("-" * 55)
    for name, g, n, c in rows:
        print(f"{name:<26}{g:>10.2f}{n:>9.2f}{c:>10.1%}")
    print()

    n_trials = len(read_trials())
    print(f"lifetime trials in trials.jsonl: {n_trials}")
    print()

    # --- deflated Sharpe on the best of the search, gross and net -------------------------
    for label, streams in (("GROSS", gross_returns), ("NET", net_returns)):
        sharpes = {k: sharpe_ratio(v) for k, v in streams.items()}
        best = max(sharpes, key=lambda k: sharpes[k])
        dsr, sr0 = deflated_sharpe_ratio(streams[best], list(sharpes.values()))
        ann = np.sqrt(365)
        print(f"{label}: best = {best}")
        print(f"  observed Sharpe        {sharpes[best] * ann:>7.2f} annualised")
        print(f"  expected max from luck {sr0 * ann:>7.2f} annualised  (n={n_trials} trials)")
        print(f"  PSR  (vs zero)         {probabilistic_sharpe_ratio(streams[best]):>7.3f}")
        print(f"  DSR  (vs the search)   {dsr:>7.3f}   {'PASS' if dsr > 0.95 else 'FAIL (<0.95)'}")
        print()

    # --- walk-forward: would choosing among these in real time have worked? --------------
    wf = walk_forward(net_returns, train_years=3.0, test_years=1.0)
    print(wf.summary())
    print()

    # --- SPA: does the best candidate beat doing nothing, or beat holding BTC? ------------
    btc = buy_and_hold(prices, symbols=["BTC/USDT"], costs=CostModel(), initial_capital=CAPITAL)
    cash = pd.Series(0.0, index=next(iter(net_returns.values())).index)

    for bench_name, bench in (("cash", cash), ("hold BTC", btc.returns)):
        p = spa_test(bench, net_returns, reps=2000)
        verdict = "beats it" if p["pvalue_consistent"] < 0.05 else "does NOT beat it"
        print(
            f"SPA vs {bench_name:<9} consistent p = {p['pvalue_consistent']:.3f}  "
            f"-> best candidate {verdict}"
        )


if __name__ == "__main__":
    main()
